version: 2.1

orbs:
  node: circleci/node@4.1.0
  codecov: codecov/codecov@1.0.2

jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: yarn test
      - codecov/upload:
          file: './coverage/clover.xml'

workflows:
  test:
    jobs:
      - test
